### PR TITLE
Changed table with DD/MM/YY and blog link.

### PR DESCRIPTION
**Pull request by sidntrivedi012**

### CODE REVIEW

**Comment by sidntrivedi012** [comment]
@darkHarry  @ryzokuken 
Added blog link to the meetup topic and made the details somewhat concise so that the table may be readable in raw form.Made the date in DD/MM/YY format to make it fit in one line.
I have one more idea to add the github resources link to the topic and make a separate column for the blog links.
Please take a look and suggest.

**Comment by sidntrivedi012** [comment]
screenshot from 2018-09-23 16-19-32

**Comment by sidntrivedi012** [comment]
@ryzokuken Made the changes. Added a new heading for table since `Meetups` had already been used as the main heading. Please review.

**Comment by saranshbarua** [comment]
This looks good

**Comment by sidntrivedi012** [comment]
@ryzokuken @saranshbarua @darkHarry Added today's meetup row. Will update the blog link as soon as it is posted. Please review.

**Pull request merged**
